version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8090:80"
      - "8091:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mired

  db:
    image: postgres:15
    container_name: sysacad-app
    restart: always
    environment:
      POSTGRES_DB: sysacad
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_user
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mired

  redis:
    image: redis:alpine
    container_name: sysacad-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mired

  gestion-service:
    build: ./microservices/gestion-service
    image: gestion-service:1.0.0
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: sysacad
      DB_USER: postgres_user
      DB_PASSWORD: postgres_user
      PORT: 3001
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - mired
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gestion-service.rule=Host(`gestion.localhost`)"
      - "traefik.http.services.gestion-service.loadbalancer.server.port=3001"
      # Middleware: Rate Limit (10 req/s, burst 5)
      - "traefik.http.middlewares.gestion-service-ratelimit.ratelimit.average=10"
      - "traefik.http.middlewares.gestion-service-ratelimit.ratelimit.burst=5"
      # Middleware: Retry (3 intentos)
      - "traefik.http.middlewares.gestion-service-retry.retry.attempts=3"
      # Middleware: Circuit Breaker (Corta si 50% de respuestas son error 500)
      - "traefik.http.middlewares.gestion-service-cb.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.5"
      # Aplicar los middlewares al router
      - "traefik.http.routers.gestion-service.middlewares=gestion-service-ratelimit,gestion-service-retry,gestion-service-cb"

volumes:
  pgdata:

networks:
  mired:
    name: mired